version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            unzip awscliv2.zip && \
            sudo ./aws/install && \
            echo Start deploy for ALB && \

            sudo apt update && \
            sudo apt install apt-transport-https ca-certificates curl software-properties-common && \
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" && \
            apt-cache policy docker-ce && \
            sudo apt install docker-ce && \
            sudo systemctl status docker && \

            aws ecr-public get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin public.ecr.aws/o2e6u6n6 && \
            sudo docker build -t rahul-react-js:success . && \
            sudo docker tag rahul-react-js:success public.ecr.aws/o2e6u6n6/rahul-ecr:success && \
            sudo docker push public.ecr.aws/o2e6u6n6/rahul-ecr:success && \
            aws ecs update-service --cluster rahul-cluster --service rahul-reactjs-service --force-new-deployment && \
            echo Deploy end
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
