version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            unzip awscliv2.zip && \
            sudo ./aws/install && \
            echo Start deploy for ALB && \

            sudo apt-get update && \
            sudo apt-get install \
            ca-certificates \
            curl \
            gnupg \
            lsb-release && \
            sudo mkdir -p /etc/apt/keyrings && \
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
            sudo apt-get update && \
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin && \

            aws ecr-public get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin public.ecr.aws/o2e6u6n6 && \
            sudo docker build -t rahul-react-js:success . && \
            sudo docker tag rahul-react-js:success public.ecr.aws/o2e6u6n6/rahul-ecr:success && \
            sudo docker push public.ecr.aws/o2e6u6n6/rahul-ecr:success && \
            aws ecs update-service --cluster rahul-cluster --service rahul-reactjs-service --force-new-deployment && \
            echo Deploy end
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
